include: package:very_good_analysis/analysis_options.yaml

# La inclusión de very_good_analysis ya cubre las reglas de flutter_lints 
# y muchas otras buenas prácticas. 
# Puedes descomentar y ajustar reglas específicas aquí si es necesario
# sobrescribir las de very_good_analysis.

linter:
  rules:
    # Ejemplo de sobrescritura (si fuera necesario):
    # avoid_print: false 

analyzer:
  # Configuración existente del analizador
  errors:
    invalid_annotation_target: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  language:
    strict-casts: true
    strict-raw-types: true
