# Usa las reglas recomendadas por el equipo de Flutter.
# https://flutter.dev/docs/development/tools/linter
include: package:flutter_lints/flutter.yaml

# La inclusión de very_good_analysis ya cubre las reglas de flutter_lints 
# y muchas otras buenas prácticas. 
# Puedes descomentar y ajustar reglas específicas aquí si es necesario
# sobrescribir las de very_good_analysis.

linter:
  # Puedes añadir reglas específicas aquí si quieres desviarte de las recomendaciones base.
  rules:
    # Ejemplo:
    # avoid_print: false

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  language:
    # Estas configuraciones refuerzan la seguridad de tipos.
    strict-casts: true
    strict-raw-types: true
  errors:
    # Puedes seguir ignorando errores específicos si es necesario
    invalid_annotation_target: ignore
