include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_declare_return_types
    - avoid_print
    - avoid_empty_else
    - avoid_redundant_argument_values
    - avoid_type_to_string
    - cancel_subscriptions
    - close_sinks
    - comment_references
    - directives_ordering
    - package_api_docs
    - prefer_const_constructors
    - prefer_final_fields
    - test_types_in_equals
    - throw_in_finally
    - unawaited_futures
    - unnecessary_null_checks
    - use_key_in_widget_constructors

analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  language:
    strict-casts: true
    strict-raw-types: true
