name: arcinus
description: "Aplicaci贸n para gesti贸n de academias deportivas."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  
  # Firebase
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  firebase_analytics: ^10.8.5
  
  # Estado y DI
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  
  # Modelos
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  
  # Navegaci贸n
  go_router: ^13.2.0
  
  # UI y Tema
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  
  # Utilidades
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  logger: ^2.0.2+1
  firebase_storage: ^11.7.7
  image_picker: ^1.1.2
  flutter_launcher_icons: ^0.14.3
  shared_preferences: ^2.5.3
  uuid: ^4.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Testing
  mocktail: ^1.0.3
  fake_cloud_firestore: ^2.5.2
  
  # Generadores de c贸digo
  build_runner: ^2.4.8
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.9
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/Logo_black.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/Logo_black.png"
