name: arcinus
description: "Aplicación para gestión de academias deportivas."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  cached_network_image: ^3.3.1
  camera: ^0.11.1
  cloud_firestore: ^4.15.4
  firebase_analytics: ^10.8.5
  firebase_auth: ^4.17.4
  firebase_core: ^2.25.4
  firebase_storage: ^11.7.7
  fl_chart: ^0.70.2
  fpdart: ^1.1.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  flutter_launcher_icons: ^0.14.3
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  flutter_svg: ^2.0.9
  freezed_annotation: ^2.4.4
  go_router: ^15.1.1
  google_fonts: ^6.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.6.1
  image: ^4.5.4
  image_picker: ^1.1.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logger: ^2.0.2+1
  path_provider: ^2.1.5
  reactive_forms: ^17.0.1
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  uuid: ^4.5.1
  http: ^1.2.1
  flutter_dotenv: ^5.1.0
  freezed: ^2.5.7
  flutter_bloc: ^9.1.1

dev_dependencies:
  build_runner: ^2.4.14
  fake_cloud_firestore: ^2.5.2
  flutter_lints: ^5.0.0
  very_good_analysis: ^6.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1

  # Testing
  mocktail: ^1.0.3
  riverpod_generator: ^2.3.9

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/config/
    - .env
    - env.file
    - lib/l10n/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/Logo_black.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/Logo_black.png"
