// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2Ki-yuAQoV6tdMX0qP1OtCqltnzypr60',
    appId: '1:699815604070:web:97bebf43cdec076cbf62a7',
    messagingSenderId: '699815604070',
    projectId: 'arcinus-f5f88',
    authDomain: 'arcinus-f5f88.firebaseapp.com',
    databaseURL: 'https://arcinus-f5f88-default-rtdb.firebaseio.com',
    storageBucket: 'arcinus-f5f88.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIPUXI5rx1XWQVviY57uwpqL2KadMyKco',
    appId: '1:699815604070:android:0d6a9681128ca389bf62a7',
    messagingSenderId: '699815604070',
    projectId: 'arcinus-f5f88',
    databaseURL: 'https://arcinus-f5f88-default-rtdb.firebaseio.com',
    storageBucket: 'arcinus-f5f88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGn9IqbR08gjgpGnk5QhPR8Z1MR436ZwU',
    appId: '1:699815604070:ios:b50c001256d4e9bbbf62a7',
    messagingSenderId: '699815604070',
    projectId: 'arcinus-f5f88',
    databaseURL: 'https://arcinus-f5f88-default-rtdb.firebaseio.com',
    storageBucket: 'arcinus-f5f88.firebasestorage.app',
    iosBundleId: 'com.example.arcinus',
  );
}
